name: voyage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  easy_localization: ^3.0.3
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  vibration: ^1.8.1
  carousel_slider: ^5.0.0
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/clock.png
    - images/light-2.png
    - images/light-1.png
    - images/background.png
    - images/profil.png
    - images/contact.png
    - images/deconnexion.png
    - images/gallerie.png
    - images/meteo.png
    - images/parametres.png
    - images/pays.png
    - images/rain.png
    - images/snow.png
    - images/clouds.png
    - images/clear.png
    - assets/sounds/clap.mp3
    - assets/lang/