// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvuvKuAXzC0VfdxDlNGAdpZTx6eyqwhE',
    appId: '1:543356334261:web:884d8abb0d0768689d0efc',
    messagingSenderId: '543356334261',
    projectId: 'voyage-85171',
    authDomain: 'voyage-85171.firebaseapp.com',
    storageBucket: 'voyage-85171.firebasestorage.app',
    measurementId: 'G-L73CRR433B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVR9EnE2xji2db8RlC-en0YaOXkTr0rA',
    appId: '1:543356334261:android:2b0a2ad6591365419d0efc',
    messagingSenderId: '543356334261',
    projectId: 'voyage-85171',
    storageBucket: 'voyage-85171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBWIeIAcKNK-cYBktpJWfX_MhaIOU718',
    appId: '1:543356334261:ios:23340a38e36c33fb9d0efc',
    messagingSenderId: '543356334261',
    projectId: 'voyage-85171',
    storageBucket: 'voyage-85171.firebasestorage.app',
    iosBundleId: 'com.example.voyage',
  );
}
